### ISSUE TITLE
Protv addon down

### ISSUE THREAD

**Issue by ursan2003** [viorel-m/kodi-repo#1]
Salut puternice,multe multumiri pentru munca depusa si multe felicitari
addonurile tare is super si ne fac viata mai usoara
am vazut ca addonului de protv ia sarit lantzul si e mort totul
Se mai poate aduce la viatza?

Best regards

**Comment by viorel-m** [comment]
Salut,
nu stiu sigur, deocamdata l-am oprit, pana am timp sa ma ocup cum trebuie de el. Sper sa il rezolv.

**Comment by viorel-m** [comment]
Rezolvat

**Comment by ursan2003** [comment]
Multumesc puternice

**Comment by marieryro** [comment]
Salut. Nu am vrut sa te deranjez deoarece am vazut ca ai mai facut tu ceva update pe hindilover. Am discutat cu adminul sitului si mi-a spus ca lucreaza la site, au fost schimbari majore. Si azi mi-a confirmat ca inca nu au terminat treaba. Din ce vad eu pe addon merge partial probabil la ultimul tau update nu aveau inca seriale turcesti in desfasurare si seriale turcesti terminate, care se gasesc acum undeva in stanga paginii pe site. Mai asteapta cateva zile si cand ai timp mai arunca o privire pe site. Cred ca nu are sens sa faci acum un update daca tot nu au terminat treaba.  Un alt addon care este foarte interesant. pe langa cele de care am discutat. este TV Mania BG acolo eu ma uit la sport. Sunt super incantat ca merge sky-urile, chiar foarte bine, dar din pacate altele nu prea merg. Rai si Fox merg, Diema si Arena nu merg niciunele, la fel Eurosport, SportKlub care merge din cand si cand. Daca mai poti face ceva si pe acolo e bine daca  nu eu sunt multumit cu Sky-urile. Tinem legatura. Multumesc pentru ca din timpul tau liber ne oferi noua ceva bun :))  Te rog sa-mi raspunzi la acest mail la adresa mariusbaltaretu@yahoo.com, este adresa pe care intru zilnic si putem comnica mai bine . Am vrut sa-ti trimit mail de pe ea dar nu intelegeam pe ce adresa sa trimit  :)) si decat sa mai chinui mai bine iti dau adresa mea folosita zi de zi.

Cu stima, Marius
