### ISSUE TITLE
Live TV down

### ISSUE THREAD

**Issue by adrianignat** [viorel-m/kodi-repo#2]
Salut,

In primul rand felicitari si multumesc pentru efortul depus.
De cateva zile nu mai merge nimic live tv.  Eu folosesc cel mai mult plugin-ul de Digi24. Merg emisiunile si merge si Digi24 Brasov Live, insa Digi 24 Live nu functioneaza.

Recent OSCM a facut un nou update, am crezut ca e de la asta, insa am facut revert la o versiune mai veche si nu merge nici cu versiunea veche.

Spune-mi, te rog, daca pot sa te ajut cumva sa il punem pe picioare. Imi e de mare ajutor plugin-ul facut de tine.

Mersi.

**Comment by viorel-m** [comment]
Salut,
 am testat pe cateva device-uri si cel putin la mine functioneaza, trimite-mi un log (kodi.log), dupa ce incerci digi24, sa vedem ce zice la tine.

**Comment by adrianignat** [comment]
Zice asa, la sfarsitul logului:

07:22:22.293 T:1959052208   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://82.76.40.81:80/digi24edge/digi24hdhqhls/index.m3u8
07:22:22.359 T:1959052208  NOTICE: VideoPlayer: Opening: http://82.76.40.81:80/digi24edge/digi24hdhqhls/index.m3u8
07:22:22.360 T:1959052208 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
07:22:32.362 T:1959052208   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://82.76.40.81:80/digi24edge/digi24hdhqhls/index.m3u8
07:22:32.363 T:1470297072  NOTICE: Creating InputStream
07:22:42.374 T:1470297072   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
07:22:42.374 T:1470297072   ERROR: CCurlFile::Open failed with code 0 for http://82.76.40.81:80/digi24edge/digi24hdhqhls/index.m3u8
07:22:42.375 T:1470297072  NOTICE: Creating Demuxer
07:22:47.489 T:1470297072   ERROR: OpenDemuxStream - Error creating demuxer

La ping digi24 eu vad alt ip:
Pinging digi24.ro [81.196.8.46]

Eu sunt pe o retea din UK, dar pe net merge live digi24.

[kodi.txt](https://github.com/viorel-m/kodi-repo/files/773383/kodi.txt)

**Comment by viorel-m** [comment]
Ok, din cate vad ai timeout pe linkurile alea, o sa incerc sa schimb modul de abordare

**Comment by adrianignat** [comment]
Multumesc mult. Daca pot sa ajut cu ceva, let me know.

**Comment by viorel-m** [comment]
Am prins putin timp liber, testeaza ultima versiune, vezi cum iti merge

**Comment by adrianignat** [comment]
Nu vad niciun commit nou pe https://github.com/viorel-m/kodi-repo/tree/master/plugin.video.digi24

Ultima versiune e tot 1.1.6.

**Comment by viorel-m** [comment]
forteaza actualizarea sau asteapta sa se faca manual, daca ai repo instalat.

**Comment by adrianignat** [comment]
Am facut update, dar tot nu merge :(

07:28:48.775 T:1959052208   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://82.76.40.81:80/digi24edge/digi24hdhqhls/index.m3u8|Referer=http://www.digi24.ro/static/js/vendor/jwplayer-7.2.2-lincenced/jwplayer.flash.swf&User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11&Accept-Language=Accept-Language: ro,en-US;q=0.7,en;q=0.3&Accept-Encoding=gzip, deflate&Host=82.76.40.81:80
07:28:48.840 T:1959052208  NOTICE: VideoPlayer: Opening: http://82.76.40.81:80/digi24edge/digi24hdhqhls/index.m3u8|Referer=http://www.digi24.ro/static/js/vendor/jwplayer-7.2.2-lincenced/jwplayer.flash.swf&User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11&Accept-Language=Accept-Language: ro,en-US;q=0.7,en;q=0.3&Accept-Encoding=gzip, deflate&Host=82.76.40.81:80
07:28:48.840 T:1959052208 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
07:28:58.841 T:1959052208   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://82.76.40.81:80/digi24edge/digi24hdhqhls/index.m3u8|Referer=http://www.digi24.ro/static/js/vendor/jwplayer-7.2.2-lincenced/jwplayer.flash.swf&User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11&Accept-Language=Accept-Language: ro,en-US;q=0.7,en;q=0.3&Accept-Encoding=gzip, deflate&Host=82.76.40.81:80
07:28:58.843 T:1448080368  NOTICE: Creating InputStream
07:29:08.855 T:1448080368   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
07:29:08.856 T:1448080368   ERROR: CCurlFile::Open failed with code 0 for http://82.76.40.81:80/digi24edge/digi24hdhqhls/index.m3u8|Referer=http://www.digi24.ro/static/js/vendor/jwplayer-7.2.2-lincenced/jwplayer.flash.swf&User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11&Accept-Language=Accept-Language: ro,en-US;q=0.7,en;q=0.3&Accept-Encoding=gzip, deflate&Host=82.76.40.81:80
07:29:08.857 T:1448080368  NOTICE: Creating Demuxer
07:29:13.969 T:1448080368   ERROR: OpenDemuxStream - Error creating demuxer

**Comment by viorel-m** [comment]
ca sa nu ne mai agitam degeaba, testeaza digi live in browser si vezi daca îți merge. Daca nu merge, e de la tine si nu am ce sa rezolv :)

**Comment by adrianignat** [comment]
Da, am testat asta si merge in browser.

Merge si http://82.76.40.81:80/digi24edge/digi24hdhqhls/index.m3u8. Adica downloadeaza playlist-ul.

**Comment by viorel-m** [comment]
Da, scuze, am facut o greseala in ultimul update si tot pe calea aia o lua :)
Incearca noul update: 1.1.8

**Comment by adrianignat** [comment]
Merge acum. A trebuit sa-l updatez manual, nu stiu de ce nu vedea versiunea 1.1.8 in repo.

Yey! Felicitari. Mersi mult.

Crezi ca aceleasi modificari sunt necesare si pentru TVR si ProTv (la protv nu merg emisiunile, desi le vad acolo)?

**Comment by razzan** [comment]
In primul rand tin sa iti multumesc pentru addonuri. Sunt foarte utile
Vreau sa sesizez si eu o problema care a aparut la aplicatia digi24 pe kodi kryptonite. Dupa update 1.1.7 a aparut o problema la kodi kryptonite audio din emisiunile inregistrate digi24. Cu 1.1.8 nu s-a rezolvat. Am revenit la 1.1.6 si problema s-a rezolvat.

**Comment by viorel-m** [comment]
@adrianignat nu promit, dar o sa incerc, daca nu cumva sunt blocate pe romania
@razzan nu am fost atent si la audio, am testat fara sonor, se rezolva ;)

**Comment by viorel-m** [comment]
S-a rezolvat in 1.1.9 viorel-m/kingul-repo@9bbd456ff2ba609de43ec5c470a234192dd548eb, am adaugat si setari pentru calitatea show-urilor inregistrate.
tvr si protv fac obiectul altei probleme, pe asta am inchis-o ;)

**Comment by viorel-m** [comment]
@adrianignat  sa imi trimiti un log cu erori de la protv si tvr te rog, in alt issue, ca sa vad care e problema
