### ISSUE TITLE
ProTv Emisiuni nu merge

### ISSUE THREAD

**Issue by adrianignat** [viorel-m/kodi-repo#3]
Salut,

Revin cu un log pentru ProTv. Din ce am incercat eu, partea cu Emisiuni nu merge nimic, dar de la seriale am incercat Las Fierbinti si a mers un episod.

Am incercat si Tvr Live, dar ala se pare ca nu face nimic si nu apare nici in log.

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'm3url' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.protvro/default.py", line 227, in <module>
                                                SXVIDEO_GENERIC_PLAY(url, icon)
                                              File "/home/osmc/.kodi/addons/plugin.video.protvro/default.py", line 59, in SXVIDEO_GENERIC_PLAY
                                                for line in urllib2.urlopen(m3url):
                                            UnboundLocalError: local variable 'm3url' referenced before assignment
                                            -->End of Python script error report<--

[kodi.txt](https://github.com/viorel-m/kodi-repo/files/786090/kodi.txt)

**Comment by viorel-m** [comment]
Salut, 
sa imi spui te rog la ce episod iti da eroarea asta.
Atentie ca nu toate emisiunile au video la liber
